### ISSUE TITLE
Initialize disk not happening automatically after applying CIS principals

### ISSUE THREAD

**Issue by vivekbangare** [ansible-lockdown/Windows-2022-CIS#30]
**Issue**
After applying cis principal from devel branch, I was not able to add extra volumes to my ec2 machine

**Expected Behavior**
It should automatically initialize and used by Local Disk Manager such that it can access it.

**Actual Behavior**
Not able to initialize automatically, need to initialize manually

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.16.3
- Host Python Version: Python 3.12.1
- Ansible Server Python Version: Python 3.12.1
![b533b472-db93-4336-8374-960288b74f76](https://github.com/ansible-lockdown/Windows-2022-CIS/assets/57985878/355b53a6-024f-4463-a7d4-591e8fa760c1)

**Comment by frederickw082922** [comment]
Good day @vivekbangare ! Thank you for submitting the issue. We have not received any feedback on this anomaly besides yourself. We are going to investigate this behavior. Unfortunately, it seems to be your environment. Best wishes.
