### ISSUE TITLE
Rule 1.1.4 and 1.1.6

### ISSUE THREAD

**Issue by animatco** [ansible-lockdown/Windows-2022-CIS#48]
**Describe the Issue**
If the "RelaxMinimumPasswordLengthLimits" is not set prior to the "MinimumPasswordLength" an error occurs if the password is set beyond 14 characters.

**Expected Behavior**
Minimum Password length larger than 14 Characters is allowed

**Actual Behavior**
Ansible Errors when attempting to set, with a missing secedit.ini file error.

**Control(s) Affected**
Rule 1.1.4 and 1.1.6
Environment (please complete the following information):

branch being used: devel
Ansible Version: 2.16.3
Host Python Version: 3.12.3
Ansible Server Python Version: 3.12.3
Additional Details:
Additional Notes
Anything additional goes here

Possible Solution
change order of run so that 1.1.6 runs 1st then 1.1.4

**Comment by MrSteve81** [comment]
Great find in 2019 they have removed RelaxMinimumPasswordLengthLimits dont think they are going to remove it in 2022 this will be updated in the coming releases.

**Comment by MrSteve81** [comment]
I also figured out today that it is a level1 - member server profile so i will also be adding the correct when statements for it so it only applies to member servers.  Not domain controllers.

**Comment by MrSteve81** [comment]
This will be pushed to devel today.  Sorry about the delays!

**Comment by MrSteve81** [comment]
Pushed to Devel.
