### ISSUE TITLE
Window Registry Key Name Mismatch

### ISSUE THREAD

**Issue by msachikanta** [ansible-lockdown/Windows-2022-CIS#51]
**Describe the Issue**
During my test, found couple registry key name are not matching with CIS Benchmark records. For example:
~~~
Rule - 2.3.10.8
Key Name - \System\Currentcontrolset\Control\Securepipeservers\Winreg\AllowedExactpaths

Rule - 2.3.10.9
Key Name - \System\Currentcontrolset\Control\Securepipeservers\Winreg\Allowedpaths

Rule - 18.6.14.1
Key Name - \Software\Policies\Microsoft\Windows\Networkprovider\Hardenedpaths

Rule - 18.6.21.1
Key Name - \Software\Policies\Microsoft\Windows\Wcmsvc\Grouppolicy
~~~

**Expected Behavior**
According to CIS Benchmark records they should be as below:
~~~
Rule - 2.3.10.8
Key Name - \SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedExactPaths

Rule - 2.3.10.9
Key Name - \SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedPaths

Rule - 18.6.14.1
Key Name - \SOFTWARE\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths

Rule - 18.6.21.1
Key Name - \SOFTWARE\Policies\Microsoft\Windows\WcmSvc\GroupPolicy
~~~

**Control(s) Affected**
Following are the affected controls:
~~~
Rule - 2.3.10.8
Rule - 2.3.10.9
Rule - 18.6.14.1
Rule - 18.6.21.1
~~~

**Environment (please complete the following information):**

- branch being used: devel

**Additional Notes**
If these key names can be corrected, that will be really great.

**Possible Solution**
Rename the registry key names according to CIS Benchmark records.

**Comment by MrSteve81** [comment]
These will be fixed in a branch im working on today that should hopefully be pushed to devel.

**Comment by MrSteve81** [comment]
Pushed to Devel.
